import AdminSidebar from "@/components/shared/AdminSidebar"
import Provider from "../Provider";
import { Inter } from "next/font/google";
import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <Provider>
         
      <main className="flex flex-row ">
        <AdminSidebar/>
        <section className="overflow-x-hidden w-full">
          <div className="w-full h-full">
            {children}
          </div>
        </section>
      </main>

 
      </Provider>
    </body>
  </html>
  )
}
